blank_issues_enabled: false
contact_links:
  - name:  â” Ask a question
    url: https://github.com/PatrickF1/fzf.fish/discussions/new
    about: Get help with using the plugin
  - name: ğŸ’¡ Idea
    url: https://github.com/PatrickF1/fzf.fish/discussions/new
    about: Suggest a new feature or an improvement to existing features
